/**
 * The Rayu login gate in HEADLESS mode.
 *
 * Why this exists: the gate `rayuLoginGateMessage()` was enforced in exactly one
 * place, `utils/processUserInput/processUserInput.ts`, which is the interactive
 * REPL input path. Nothing under `src/entrypoints/` or `src/cli/print.ts` called
 * it, so every headless consumer — the SDK, CCR, and the Rayucode VS Code
 * extension, which spawns `--print --input-format=stream-json` — could run turns
 * while signed out. The bug was found by launching the extension and being able
 * to send a prompt with no login.
 *
 * These tests pin the conditions against the REPL's, because the two must agree:
 * a prompt gated in one and allowed in the other is worse than no gate at all.
 */
import { describe, expect, test } from 'bun:test'
import { headlessLoginGateMessage } from '../src/cli/print.ts'
import type { QueuedCommand } from '../src/types/textInputTypes.ts'

const GATE = 'You need to sign in to use Rayu.'

/** A gate that always refuses, i.e. "signed out". */
const signedOut = () => GATE
/** A gate that always allows, i.e. signed in, or OAuth off, or an API key. */
const signedIn = () => null

function cmd(overrides: Partial<QueuedCommand> = {}): QueuedCommand {
  return { value: 'hello', mode: 'prompt', ...overrides } as QueuedCommand
}

describe('a signed-out user is refused', () => {
  test('a plain prompt is gated', () => {
    expect(headlessLoginGateMessage(cmd(), signedOut)).toBe(GATE)
  })

  test('a prompt sent as content blocks is gated', () => {
    // The extension sends structured content, not always a bare string.
    expect(
      headlessLoginGateMessage(
        cmd({ value: [{ type: 'text', text: 'hello' }] }),
        signedOut,
      ),
    ).toBe(GATE)
  })

  test('non-text blocks do not defeat the gate', () => {
    // An image-only prompt has no text to inspect; it must still be gated
    // rather than falling through the slash-command check.
    expect(
      headlessLoginGateMessage(
        cmd({
          value: [
            {
              type: 'image',
              source: { type: 'base64', media_type: 'image/png', data: 'x' },
            },
          ],
        }),
        signedOut,
      ),
    ).toBe(GATE)
  })
})

describe('a signed-in user is never refused', () => {
  test('a plain prompt proceeds', () => {
    expect(headlessLoginGateMessage(cmd(), signedIn)).toBeNull()
  })

  test('the gate is the only thing consulted', () => {
    // `signedIn` stands for all three of the real gate's escape hatches: OAuth
    // disabled, a valid session, or a usable Rayu API key. This file must not
    // re-implement that decision — rayuSession.ts owns it.
    expect(headlessLoginGateMessage(cmd({ value: 'anything' }), signedIn)).toBeNull()
  })
})

describe('slash commands stay reachable while signed out', () => {
  test('/login is exempt, so the gate is recoverable rather than a lockout', () => {
    expect(headlessLoginGateMessage(cmd({ value: '/login' }), signedOut)).toBeNull()
  })

  test('/connect is exempt, for the API-key path', () => {
    expect(
      headlessLoginGateMessage(cmd({ value: '/connect' }), signedOut),
    ).toBeNull()
  })

  test('leading whitespace does not hide a slash command', () => {
    // Matches the REPL's `inputString.trimStart().startsWith('/')`.
    expect(
      headlessLoginGateMessage(cmd({ value: '   /login' }), signedOut),
    ).toBeNull()
  })

  test('a slash command in content-block form is exempt too', () => {
    expect(
      headlessLoginGateMessage(
        cmd({ value: [{ type: 'text', text: '/login' }] }),
        signedOut,
      ),
    ).toBeNull()
  })

  test('skipSlashCommands means the text is NOT a command, so it IS gated', () => {
    // Remote sources set this so `/`-prefixed text is treated literally. Letting
    // it through as "a slash command" would be a bypass: any client could prefix
    // a slash and skip the gate.
    expect(
      headlessLoginGateMessage(
        cmd({ value: '/login', skipSlashCommands: true }),
        signedOut,
      ),
    ).toBe(GATE)
  })
})

describe('engine-generated input is not user input, so it is not gated', () => {
  test('isMeta prompts pass', () => {
    // Proactive ticks, teammate messages and resource updates route through the
    // same queue but are generated by the engine, not typed by a user.
    expect(
      headlessLoginGateMessage(cmd({ isMeta: true }), signedOut),
    ).toBeNull()
  })

  test('bridgeOrigin prompts pass, having cleared the remote client’s own auth', () => {
    expect(
      headlessLoginGateMessage(cmd({ bridgeOrigin: true }), signedOut),
    ).toBeNull()
  })

  test.each(['task-notification', 'orphaned-permission'] as const)(
    '%s mode passes',
    mode => {
      expect(
        headlessLoginGateMessage(cmd({ mode } as Partial<QueuedCommand>), signedOut),
      ).toBeNull()
    },
  )
})

describe('the default gate is the shared one, not a copy', () => {
  test('called with no injected gate it consults rayuSession', () => {
    // The hermetic test preload forces RAYU_OAUTH_DEFAULT off
    // (scripts/preload.test.ts), so with no USE_RAYU_OAUTH set the real gate
    // returns null. The assertion that matters is that it RESOLVES rather than
    // throwing — i.e. the production call path is wired to rayuSession.
    expect(() => headlessLoginGateMessage(cmd())).not.toThrow()
  })
})
