/**
 * Tests for IPC_RUNTIME_ACTION round trip (Task 14).
 *
 * Verifies:
 *  1. Each action type serializes correctly
 *  2. CLI handler returns success for valid actions
 *  3. CLI handler returns error for invalid action type
 *  4. requestId is echoed back in the response
 *  5. Extension's sendRuntimeAction method works end-to-end
 */
import { expect, test } from 'bun:test'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  startSessionIpc,
  stopSessionIpc,
  getSessionIpcInfo,
  registerIpcHandler,
} from '../src/ipc/sessionServer.js'
import { attachToCliSession, type AttachmentCallbacks } from '../src/vscode/host/attach/cliAttachment.js'
import {
  IPC_CAPABILITIES,
  IPC_RUNTIME_ACTION,
  ATTACHED_RUNTIME_CAPABILITIES,
} from '../src/vscode/shared/attachChannels.js'
import type {
  RuntimeAction,
  RuntimeActionRequest,
  RuntimeActionResponse,
} from '../src/vscode/shared/attachProtocol.js'

function noopCallbacks(): AttachmentCallbacks {
  return {
    onStreamStart() {},
    onStreamDelta() {},
    onStreamThinking() {},
    onStreamEnd() {},
    onActivity() {},
    onPermissionRequest() {},
    onPermissionDismiss() {},
    onClosed() {},
  }
}

async function withFixture(
  run: (target: {
    pid: number
    sessionId: string
    cwd: string
    startedAt: number
    ipcAddress: string
    ipcToken: string
  }) => Promise<void>,
): Promise<void> {
  const directory = mkdtempSync(join(tmpdir(), 'rayucode-runtime-action-'))
  const old = process.env.RAYU_CONFIG_DIR
  process.env.RAYU_CONFIG_DIR = directory
  try {
    await startSessionIpc()
    const info = getSessionIpcInfo()!
    await run({
      pid: process.pid,
      sessionId: 'fixture-action',
      cwd: directory,
      startedAt: Date.now(),
      ipcAddress: info.address,
      ipcToken: info.token,
    })
  } finally {
    await stopSessionIpc()
    if (old === undefined) delete process.env.RAYU_CONFIG_DIR
    else process.env.RAYU_CONFIG_DIR = old
    rmSync(directory, { recursive: true, force: true })
  }
}

function makeActionHandler(
  onAction: (req: RuntimeActionRequest) => RuntimeActionResponse,
): () => void {
  return registerIpcHandler(IPC_RUNTIME_ACTION, payload => {
    const req = payload as RuntimeActionRequest
    return onAction(req)
  })
}

test('RuntimeActionRequest serializes all action types correctly', () => {
  const actions: RuntimeAction[] = [
    { type: 'change_model', modelId: 'claude-3-5-sonnet', providerId: 'anthropic' },
    { type: 'toggle_thinking', enabled: true },
    { type: 'set_effort', effort: 'high' },
    { type: 'update_permission_mode', mode: 'allow' },
    { type: 'reconnect_mcp', serverId: 'github' },
  ]
  for (const action of actions) {
    const req: RuntimeActionRequest = { requestId: 'test-id', action }
    const serialized = JSON.parse(JSON.stringify(req)) as RuntimeActionRequest
    expect(serialized.action.type).toBe(action.type)
    expect(serialized.requestId).toBe('test-id')
  }
})

test('sendRuntimeAction returns success response from CLI handler', async () => {
  await withFixture(async target => {
    const unregisterCaps = registerIpcHandler(IPC_CAPABILITIES, () => ATTACHED_RUNTIME_CAPABILITIES)
    const receivedActions: RuntimeAction[] = []
    const unregisterAction = makeActionHandler(req => {
      receivedActions.push(req.action)
      return { requestId: req.requestId, success: true }
    })

    let handle: Awaited<ReturnType<typeof attachToCliSession>> = null
    try {
      handle = await attachToCliSession(target, noopCallbacks())
      expect(handle).not.toBeNull()
      expect(handle!.capabilities?.features.configurationActions).toBe(true)

      const response = await handle!.sendRuntimeAction({
        type: 'toggle_thinking',
        enabled: true,
      })

      expect(response.success).toBe(true)
      expect(receivedActions).toHaveLength(1)
      expect(receivedActions[0]!.type).toBe('toggle_thinking')
    } finally {
      handle?.detach()
      unregisterCaps()
      unregisterAction()
    }
  })
})

test('requestId is echoed back in the RuntimeActionResponse', async () => {
  await withFixture(async target => {
    const unregisterCaps = registerIpcHandler(IPC_CAPABILITIES, () => ATTACHED_RUNTIME_CAPABILITIES)
    const unregisterAction = makeActionHandler(req => ({
      requestId: req.requestId,
      success: true,
    }))

    let handle: Awaited<ReturnType<typeof attachToCliSession>> = null
    try {
      handle = await attachToCliSession(target, noopCallbacks())
      const response = await handle!.sendRuntimeAction({ type: 'set_effort', effort: 'low' })
      // The requestId is a UUID generated by sendRuntimeAction; we just verify it's non-empty
      expect(typeof response.requestId).toBe('string')
      expect(response.requestId.length).toBeGreaterThan(0)
      expect(response.success).toBe(true)
    } finally {
      handle?.detach()
      unregisterCaps()
      unregisterAction()
    }
  })
})

test('CLI handler returns error response for invalid action', async () => {
  await withFixture(async target => {
    const unregisterCaps = registerIpcHandler(IPC_CAPABILITIES, () => ATTACHED_RUNTIME_CAPABILITIES)
    const unregisterAction = registerIpcHandler(IPC_RUNTIME_ACTION, payload => {
      const req = payload as RuntimeActionRequest
      return {
        requestId: req.requestId,
        success: false,
        error: 'Unknown action type.',
      }
    })

    let handle: Awaited<ReturnType<typeof attachToCliSession>> = null
    try {
      handle = await attachToCliSession(target, noopCallbacks())
      const response = await handle!.sendRuntimeAction(
        { type: 'change_model', modelId: '' } as RuntimeAction,
      )
      expect(response.success).toBe(false)
    } finally {
      handle?.detach()
      unregisterCaps()
      unregisterAction()
    }
  })
})
