# These are supported funding model platforms

# GitHub Sponsors
github: [Choeng-Rayu]

# Open Collective
# open_collective: rayu-cli

# Ko-fi
# ko_fi: rayucli

# Patreon
# patreon: rayucli

# Buy Me a Coffee
# buy_me_a_coffee: rayucli

# Custom sponsor link
custom: ['https://rayu-web.vercel.app/sponsor']
