/**
 * Typed payloads for the `rayucode:*` IPC channels added in the attach/detach
 * protocol extension (Tasks 12–15).
 *
 * ── WHY THIS IS SEPARATE FROM attachChannels.ts ────────────────────────────────
 *
 * `attachChannels.ts` is a dependency-free leaf that both the CLI engine and the
 * extension host import to share channel names and the capability map.  Adding
 * richer payload shapes here keeps that leaf small and avoids pulling in the
 * wider type universe into a file that is explicitly kept minimal.
 *
 * ── SERIALIZATION CONSTRAINT ───────────────────────────────────────────────────
 *
 * All types in this file MUST be JSON-serializable — no `Map`, no `Set`, no
 * class instances.  The IPC transport is a Unix-socket JSON protocol, and any
 * value that cannot survive `JSON.stringify → JSON.parse` round-trips will
 * silently lose data or throw.  Where the in-memory representation uses a `Map`
 * (e.g. `ConversationStateSnapshot`), the wire type carries plain arrays of
 * `[key, value]` tuples instead.
 */

// ── Task 12: Conversation snapshot ────────────────────────────────────────────

/**
 * Wire shape for `IPC_CONVERSATION_SNAPSHOT`.
 *
 * `ConversationStateSnapshot` (sessionHandle.ts) holds Maps; those cannot
 * cross the IPC boundary as-is.  This type replaces them with plain arrays.
 * The extension reconstructs Maps after deserialization.
 */
export interface AttachedConversationSnapshot {
  /** Protocol revision so older callers can detect an incompatible shape. */
  version: 1
  /**
   * Already-formatted activity messages, one entry per completed CLI turn.
   *
   * Each item is a `WrappedMessage`-compatible plain object; the receiver
   * passes them directly to `applyMirroredActivity`.
   */
  messages: unknown[]
}

// ── Task 14: Runtime action request/response ──────────────────────────────────

/**
 * Typed actions the extension can send to the attached CLI over
 * `IPC_RUNTIME_ACTION`.  Each branch is a self-describing discriminated union
 * so the CLI dispatcher can use an exhaustive `switch` without casting.
 */
export type RuntimeAction =
  | { type: 'change_model'; modelId: string; providerId?: string }
  | { type: 'toggle_thinking'; enabled: boolean }
  | { type: 'set_effort'; effort: 'low' | 'medium' | 'high' }
  | { type: 'update_permission_mode'; mode: string }
  | { type: 'reconnect_mcp'; serverId: string }

/**
 * Envelope wrapping a `RuntimeAction` sent from the extension to the CLI.
 *
 * `requestId` is generated by the sender and echoed back in
 * `RuntimeActionResponse` so a caller waiting on a specific request can
 * correlate its result even if multiple actions are in-flight.
 */
export interface RuntimeActionRequest {
  requestId: string
  action: RuntimeAction
}

/**
 * What the CLI sends back through `IPC_RUNTIME_ACTION` after processing a
 * `RuntimeActionRequest`.
 */
export interface RuntimeActionResponse {
  requestId: string
  success: boolean
  error?: string
  /** Any extra structured data the action wants to return. */
  result?: unknown
}

// ── Task 15: Runtime state snapshot ──────────────────────────────────────────

/**
 * A point-in-time view of the CLI's runtime state, pushed whenever something
 * meaningful changes.  Sent both as the initial response to
 * `IPC_RUNTIME_SNAPSHOT` and then as push notifications on
 * `IPC_RUNTIME_STATE_CHANGED`.
 *
 * ── ALL FIELDS ARE OPTIONAL AFTER `version` ────────────────────────────────────
 *
 * Older CLI builds will omit fields that didn't exist yet.  Consumers MUST
 * treat every optional field as possibly absent rather than assuming it is
 * always present, so adding a field here is backwards-compatible without a
 * protocol-version bump.
 */
export interface RuntimeStateSnapshot {
  version: 1
  sessionId: string
  timestamp: number
  model?: {
    id: string
    providerId: string
    displayName: string
    supportsThinking: boolean
  }
  permissions?: {
    mode: string
    pendingCount: number
  }
  mcp?: {
    servers: Array<{
      id: string
      name: string
      status: 'connected' | 'connecting' | 'failed' | 'pending'
      toolCount: number
    }>
  }
  thinking?: {
    enabled: boolean
    currentlyThinking: boolean
  }
  effort?: 'low' | 'medium' | 'high' | null
  worktree?: {
    active: boolean
    path: string | null
  } | null
  taskList?: {
    totalTasks: number
    completedTasks: number
    currentTask: string | null
  } | null
}
