// Rayu-CLI de-brand audit. Scans src/ for every case-insensitive "claude"
// reference and classifies each matching line into one of five buckets so the
// de-brand / de-risk work (and ORIGIN_MANIFEST.md) has a factual inventory.
//
//   MODEL_ID     — Anthropic API model identifiers (claude-opus-4, etc.). KEEP.
//   INTEROP      — reads Claude Code's own config/skills as a fallback.       KEEP.
//   PROPRIETARY  — Anthropic internal infra (telemetry, claude.ai OAuth,      REMOVE / NEUTRALIZE.
//                  CCR/upstream proxy, generated internal event schemas).
//   BRAND        — user-facing "Claude Code" / "Claude" product branding.     RENAME.
//   OTHER        — residual references not covered above (review manually).
//
// Usage: bun run scripts/claude-ref-audit.ts   → writes architecture/CLAUDE_REF_AUDIT.md
import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from 'fs'
import { join, relative } from 'path'

const ROOT = join(import.meta.dir, '..')
const SRC = join(ROOT, 'src')
const OUT = join(ROOT, 'architecture', 'CLAUDE_REF_AUDIT.md')

type Bucket = 'MODEL_ID' | 'INTEROP' | 'PROPRIETARY' | 'BRAND' | 'OTHER'

const INTEROP_FILES = [
  'utils/externalSkillDiscovery.ts',
  'services/mcp/config.ts',
  'utils/ide.ts',
  'utils/permissions/filesystem.ts',
  'utils/sandbox/sandbox-adapter.ts',
]

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const st = statSync(full)
    if (st.isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist') continue
      walk(full, acc)
    } else if (/\.(ts|tsx)$/.test(entry)) {
      acc.push(full)
    }
  }
  return acc
}

function classify(line: string, relPath: string): Bucket {
  const l = line.toLowerCase()
  // Most specific first: Anthropic model identifiers must be preserved.
  if (/claude[-.]?(opus|sonnet|haiku|instant|\d)/.test(l) || /anthropic\.claude/.test(l)) {
    return 'MODEL_ID'
  }
  // Anthropic proprietary internal infrastructure.
  if (
    /growthbook|statsig|firstparty|first_party|1p event|events_mono|claude_code_internal|claube|claubbit/.test(l) ||
    /claude\.ai|claude-ai|anthropic\.com|upstreamproxy|\bccr\b|oauth/.test(l)
  ) {
    return 'PROPRIETARY'
  }
  // Interop: reading Claude Code's own config/skills as a fallback source.
  if (
    INTEROP_FILES.some((f) => relPath.endsWith(f)) ||
    /\.claude\/skills|~\/\.claude|interop|fallback|extension/.test(l)
  ) {
    return 'INTEROP'
  }
  // User-facing product branding.
  if (/claude\s*code|claudecode|\bclaude\b/.test(l)) {
    return 'BRAND'
  }
  return 'OTHER'
}

const counts: Record<Bucket, number> = {
  MODEL_ID: 0,
  INTEROP: 0,
  PROPRIETARY: 0,
  BRAND: 0,
  OTHER: 0,
}
const byBucket: Record<Bucket, Map<string, number>> = {
  MODEL_ID: new Map(),
  INTEROP: new Map(),
  PROPRIETARY: new Map(),
  BRAND: new Map(),
  OTHER: new Map(),
}

let filesScanned = 0
for (const file of walk(SRC)) {
  filesScanned++
  const relPath = relative(SRC, file)
  const text = readFileSync(file, 'utf8')
  for (const line of text.split('\n')) {
    if (!/claude/i.test(line)) continue
    const bucket = classify(line, relPath)
    counts[bucket]++
    byBucket[bucket].set(relPath, (byBucket[bucket].get(relPath) ?? 0) + 1)
  }
}

const total = Object.values(counts).reduce((a, b) => a + b, 0)
const disposition: Record<Bucket, string> = {
  MODEL_ID: 'KEEP — Anthropic API model identifiers; renaming breaks the provider.',
  INTEROP: 'KEEP — reads Claude Code config/skills as a fallback (intentional interop).',
  PROPRIETARY: 'REMOVE / NEUTRALIZE — Anthropic internal infra (telemetry, OAuth, CCR).',
  BRAND: 'RENAME — user-facing product branding to route through constants/product.ts.',
  OTHER: 'REVIEW — residual references; classify manually.',
}

let md = `# Claude-reference audit (auto-generated)\n\n`
md += `Generated by \`scripts/claude-ref-audit.ts\`. Do not edit by hand.\n\n`
md += `Scanned **${filesScanned}** source files under \`src/\`; **${total}** lines contain "claude" (case-insensitive).\n\n`
md += `| Bucket | Lines | Disposition |\n|---|---:|---|\n`
for (const b of Object.keys(counts) as Bucket[]) {
  md += `| ${b} | ${counts[b]} | ${disposition[b]} |\n`
}
md += `\n`
for (const b of Object.keys(byBucket) as Bucket[]) {
  const entries = [...byBucket[b].entries()].sort((a, c) => c[1] - a[1])
  md += `## ${b} (${counts[b]} lines across ${entries.length} files)\n\n`
  md += `${disposition[b]}\n\n`
  for (const [f, n] of entries.slice(0, 40)) {
    md += `- \`src/${f}\` — ${n}\n`
  }
  if (entries.length > 40) md += `- …and ${entries.length - 40} more files\n`
  md += `\n`
}

mkdirSync(join(ROOT, 'architecture'), { recursive: true })
writeFileSync(OUT, md)
console.log(`claude-ref-audit: ${total} lines across ${filesScanned} files`)
for (const b of Object.keys(counts) as Bucket[]) {
  console.log(`  ${b.padEnd(12)} ${counts[b]}`)
}
console.log(`report → ${relative(ROOT, OUT)}`)
