// Rayu-CLI module-origin manifest generator.
//
// Classifies every source file under src/ into one of three provenance buckets
// to support an IP/legal review of the fork:
//
//   ORIGINAL   — first-party Rayu work (features the maintainer added):
//                collaborator swarm, image/video generation, Telegram bridge,
//                the Rayu gateway/account layer, and Rayu-branded config/UI.
//   GENERATED  — machine-generated code (protobuf schemas, etc.).
//   DERIVATIVE — the Claude Code core this project was forked from (the CLI
//                engine, TUI renderer, tool framework, providers, etc.).
//
// Classification is PATH-HEURISTIC and provided as engineering input for legal
// review — it is NOT legal advice and NOT a legal determination of authorship
// or copyright. See the caveat written into ORIGIN_MANIFEST.md.
//
// Usage:
//   bun run scripts/origin-manifest.ts           # write ORIGIN_MANIFEST.md
//   bun run scripts/origin-manifest.ts --check    # verify coverage (CI gate)
import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join, relative } from 'path'

export type Provenance = 'ORIGINAL' | 'GENERATED' | 'DERIVATIVE'

const ROOT = join(import.meta.dir, '..')
const SRC = join(ROOT, 'src')
const OUT = join(ROOT, 'ORIGIN_MANIFEST.md')

// First-party (Rayu-original) path prefixes / markers, relative to src/.
const ORIGINAL_DIR_PREFIXES = [
  'utils/swarm/',
  'coordinator/',
  'tools/AgentTool/built-in/collaborators/',
  'tools/ImageGenTool/',
  'tools/VideoGenTool/',
  'telegram/',
  'services/rayuAuth/',
  'commands/model-image-generation/',
  'commands/model-video-generation/',
  'commands/ultraplan-local/',
]
// First-party single-file markers (exact relative paths or basename patterns).
const ORIGINAL_FILE_MARKERS = [
  'commands/generate-image.ts',
  'commands/image-video.ts',
  'commands/image-editor.ts',
  'utils/rayuConfig.ts',
  'utils/rayuProviders.ts',
  'utils/agentSwarmsEnabled.ts',
  'components/RayuProviderSetup.tsx',
]

/** Classify a src-relative path into a provenance bucket. */
export function classify(relPath: string): Provenance {
  const p = relPath.replace(/\\/g, '/')
  if (p.startsWith('types/generated/')) return 'GENERATED'
  if (ORIGINAL_DIR_PREFIXES.some(d => p.startsWith(d))) return 'ORIGINAL'
  if (ORIGINAL_FILE_MARKERS.some(f => p === f)) return 'ORIGINAL'
  // Rayu-branded basenames (rayu*.ts / Rayu*.tsx) are first-party additions.
  const base = p.split('/').pop() ?? ''
  if (/^rayu/i.test(base)) return 'ORIGINAL'
  // Everything else is inherited from the forked Claude Code core.
  return 'DERIVATIVE'
}

export function walkSrc(dir: string = SRC, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist') continue
      walkSrc(full, acc)
    } else if (/\.(ts|tsx)$/.test(entry)) {
      acc.push(relative(SRC, full).replace(/\\/g, '/'))
    }
  }
  return acc
}

export function classifyAll(): {
  files: string[]
  byBucket: Record<Provenance, string[]>
} {
  const files = walkSrc().sort()
  const byBucket: Record<Provenance, string[]> = {
    ORIGINAL: [],
    GENERATED: [],
    DERIVATIVE: [],
  }
  for (const f of files) byBucket[classify(f)].push(f)
  return { files, byBucket }
}

function buildManifest(): string {
  const { files, byBucket } = classifyAll()
  const total = files.length
  const pct = (n: number) => ((100 * n) / total).toFixed(1)

  // Rough coupling metric: how many ORIGINAL files import from a DERIVATIVE
  // module (i.e. build on the forked core).
  let coupled = 0
  for (const f of byBucket.ORIGINAL) {
    const text = readFileSync(join(SRC, f), 'utf8')
    const imports = [...text.matchAll(/from\s+['"]([^'"]+)['"]/g)].map(m => m[1])
    if (
      imports.some(
        i => i.startsWith('../') || i.startsWith('src/') || i.startsWith('./'),
      )
    ) {
      coupled++
    }
  }

  let md = `# Rayu-CLI — Module Origin Manifest\n\n`
  md += `<!-- ORIGIN_MANIFEST_FILE_COUNT: ${total} -->\n`
  md += `_Auto-generated by \`scripts/origin-manifest.ts\`. Regenerate after adding/removing source files._\n\n`

  md += `> **Legal caveat — read first.** This document is **engineering input for an IP/legal review, not legal advice and not a legal determination** of authorship, ownership, or copyright. Rayu-CLI is a fork of Anthropic's **Claude Code**, which is proprietary software distributed under Anthropic's commercial terms — **not** an open-source license. Renaming symbols and removing telemetry/auth/remote code (as done in this repo) does **not**, by itself, resolve the copyright status of a derivative work. The "ORIGINAL" bucket below reflects the maintainer's own added features by file path; it is a heuristic starting point. **Consult a qualified IP/technology attorney before any commercial launch.**\n\n`

  md += `## Summary\n\n`
  md += `Scanned **${total}** source files under \`src/\`.\n\n`
  md += `| Provenance | Files | Share | Disposition |\n|---|---:|---:|---|\n`
  md += `| ORIGINAL (first-party Rayu) | ${byBucket.ORIGINAL.length} | ${pct(byBucket.ORIGINAL.length)}% | Maintainer's own IP (built on the derivative core). |\n`
  md += `| GENERATED | ${byBucket.GENERATED.length} | ${pct(byBucket.GENERATED.length)}% | Machine-generated (e.g. protobuf); provenance follows its schema source. |\n`
  md += `| DERIVATIVE (Claude Code core) | ${byBucket.DERIVATIVE.length} | ${pct(byBucket.DERIVATIVE.length)}% | Inherited from the forked upstream; the copyright-sensitive bulk. |\n\n`

  md += `## Coupling note\n\n`
  md += `**${coupled} of ${byBucket.ORIGINAL.length}** ORIGINAL files import from the local module graph, i.e. they are **built on top of the DERIVATIVE core** (the tool framework \`src/Tool.ts\`, agent framework \`src/tools/AgentTool/\`, query engine \`src/query.ts\` / \`src/QueryEngine.ts\`, the custom Ink TUI renderer \`src/ink/\`, provider adapters, and config/permission systems). The first-party features are therefore **not cleanly separable** from the derivative core as-is: lifting them onto a clean-room or permissively-licensed base would require re-implementing those shared foundations. This is the key structural fact for the legal/architecture decision.\n\n`

  md += `## De-risk actions already applied (see un-use-code/README.md)\n\n`
  md += `- Anthropic telemetry (GrowthBook/Statsig feature flags + first-party event logging) **neutralized to no-op stubs**; network exporter + GrowthBook dependency removed.\n`
  md += `- **claude.ai subscription OAuth login removed** (BYO \`ANTHROPIC_API_KEY\` and other providers retained).\n`
  md += `- **CCR upstream proxy removed**; remote-session URLs **de-pointed from claude.ai** to a Rayu-configured host.\n`
  md += `- Telemetry is **off by default** (\`RAYU_TELEMETRY\`), and an active OpenAI-compatible provider forces essential-traffic-only.\n\n`
  md += `Note: a theme color token literally named \`"claude"\` remains in ~40 UI files. It is an internal design-token identifier (not user-visible text); renaming is cosmetic and deferred to avoid churn.\n\n`

  md += `## ORIGINAL — first-party Rayu modules (${byBucket.ORIGINAL.length})\n\n`
  for (const f of byBucket.ORIGINAL) md += `- \`src/${f}\`\n`
  md += `\n`

  md += `## GENERATED (${byBucket.GENERATED.length})\n\n`
  for (const f of byBucket.GENERATED) md += `- \`src/${f}\`\n`
  md += `\n`

  md += `## DERIVATIVE — Claude Code core (${byBucket.DERIVATIVE.length})\n\n`
  md += `Too many to enumerate individually; summarized by top-level area:\n\n`
  const dirCounts = new Map<string, number>()
  for (const f of byBucket.DERIVATIVE) {
    const top = f.includes('/') ? f.split('/').slice(0, 2).join('/') : `(root)/${f}`
    dirCounts.set(top, (dirCounts.get(top) ?? 0) + 1)
  }
  for (const [d, n] of [...dirCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 40)) {
    md += `- \`src/${d}\` — ${n}\n`
  }
  md += `\n## Methodology\n\nClassification is path-heuristic (\`scripts/origin-manifest.ts\`): \`types/generated/\`→GENERATED; the maintainer's feature directories/markers and \`rayu*\`/\`Rayu*\` basenames→ORIGINAL; everything else→DERIVATIVE (the forked core). It is deliberately conservative — when unsure, a file is treated as DERIVATIVE.\n`
  return md
}

const isCheck = process.argv.includes('--check')
if (import.meta.main) {
  if (isCheck) {
  const { files } = classifyAll()
  let recorded = -1
  try {
    const m = readFileSync(OUT, 'utf8').match(/ORIGIN_MANIFEST_FILE_COUNT:\s*(\d+)/)
    if (m) recorded = parseInt(m[1], 10)
  } catch {
    console.error('✗ ORIGIN_MANIFEST.md missing — run: bun run scripts/origin-manifest.ts')
    process.exit(1)
  }
  const unclassified = files.filter(f => !['ORIGINAL', 'GENERATED', 'DERIVATIVE'].includes(classify(f)))
  if (unclassified.length > 0) {
    console.error(`✗ ${unclassified.length} unclassified file(s)`) 
    process.exit(1)
  }
  if (recorded !== files.length) {
    console.error(`✗ ORIGIN_MANIFEST.md is stale: records ${recorded} files, src has ${files.length}. Regenerate.`)
    process.exit(1)
  }
  console.log(`✓ origin manifest current: ${files.length} files, all classified.`)
} else {
  writeFileSync(OUT, buildManifest())
  const { files, byBucket } = classifyAll()
  console.log(`origin-manifest: ${files.length} files → ORIGIN_MANIFEST.md`)
  console.log(`  ORIGINAL ${byBucket.ORIGINAL.length}  GENERATED ${byBucket.GENERATED.length}  DERIVATIVE ${byBucket.DERIVATIVE.length}`)
  }
}
