import { IsEmail, IsNotEmpty, IsOptional, IsString, MaxLength } from 'class-validator'

export class LocalLoginDto {
  @IsEmail()
  @MaxLength(320)
  email!: string

  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  password!: string
}

export class RegisterDto {
  @IsEmail()
  @MaxLength(320)
  email!: string

  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  password!: string

  @IsString()
  @IsOptional()
  @MaxLength(191)
  displayName?: string
}

export class GoogleOAuthDto {
  // Google ID token from the frontend (obtained via NextAuth / Google Sign-In).
  @IsString()
  @IsNotEmpty()
  idToken!: string
}

export class ExchangeDto {
  // CSRF state generated by the CLI and round-tripped through the browser.
  @IsString()
  @IsNotEmpty()
  @MaxLength(256)
  state!: string
}

export class TokenDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(256)
  code!: string
}

export class RefreshDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(4096)
  refreshToken!: string
}
