import { IsNotEmpty, IsString, MaxLength } from 'class-validator'

export class ExchangeDto {
  // CSRF state generated by the CLI and round-tripped through the browser.
  @IsString()
  @IsNotEmpty()
  @MaxLength(256)
  state!: string
}

export class TokenDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(256)
  code!: string
}

export class RefreshDto {
  @IsString()
  @IsNotEmpty()
  @MaxLength(4096)
  refreshToken!: string
}
